### ISSUE TITLE
`uniq` causes constant recompilations and causes tooling issues

### ISSUE THREAD

**Issue by sondr3** [bitwalker/uniq#14] opened 2023-06-25 12:28 UTC
Not sure whether to report this here or in other repositories, but I made an issue in rrrene/credo#1052 that causes tooling in editors using e.g. `credo` to break. I'm a newbie Elixir programmer, so not sure whether the issue is something I can resolve or something `uniq` can do about it, but I wanted to raise this issue here just in case.

**Comment by bitwalker** [comment] 2023-06-26 19:58
I haven't ever observed this before, but I'll see if I can reproduce. As far as I'm aware, there should be no reason why `uniq` causes this and other packages don't. This seems to be something in `credo` specifically, but I'll play around a bit and see if I can reproduce first.

**Comment by sondr3** [comment] 2023-06-27 06:35
I have a repo you can use, though it's literally just the starter project from Phoenix with Credo and uniq: https://github.com/sondr3/credo_uniq_repro. It might just be my machine, but with `uniq` as a dependency it recompiles every time.

**Comment by spatrik** [comment] 2023-06-27 20:35
I'm getting the same behaviour when using Elixir 1.15/OTP 25. However, using Elixir 1.13/OTP 24 it does not recompile all the time. 

It's enough to just run `mix compile` multiple times. No changes in my own app is neccesary.

**Comment by bitwalker** [comment] 2023-06-27 21:23
With OTP 25 + Elixir 1.15.0, running `mix compile` on a clean working directory (in the `uniq` repo) compiles fully, and all subsequent `mix compile`s do not recompile anything. Likewise if I add `uniq` as a dependency to a project as a `path` dependency, no recompiles occur.

However, if I add `uniq` as a dependency, as a Hex package, I do see the recompilation issue, but I'm not sure why this happens when it is a Hex package vs local dependency. My suspicion is that it may have to do with some of the code path changes done with regard to dependencies in 1.15, but I'm not 100% sure. I'll do some more digging, but that's what I have found so far.

**Comment by bitwalker** [comment] 2023-06-27 21:52
@josevalim Heads up, there may be something of a regression with some of the compilation changes in 1.15 (or perhaps something I'm doing in `uniq` is stupid). I thought initially it might have to do with code path pruning, but that doesn't seem to be the case. For some reason the compiler needs to recompile the whole package on every `mix compile` - but only when used as a Hex package (compiling the repo on its own, or using as a `path` dependency does not exhibit the same behavior).

I suspect it has to do with the use of the `defextension` macro [defined here](https://github.com/bitwalker/uniq/blob/3df2ec076756a47926e48aec175f36b065b0c8a2/lib/macros.ex#L2) and [used here](https://github.com/bitwalker/uniq/blob/3df2ec076756a47926e48aec175f36b065b0c8a2/lib/uuid.ex#L952). The macro just expands the body inline if the given module is/can be loaded (in this case `Ecto.ParameterizedType`. The part that's really tripping me out is that the issue here is only observable when using `uniq` as a Hex dependency, and I'm not even sure if it's this macro that's causing it (though I would be surprised if it's something else).

Is this expected behavior as of 1.15? If so, do you have any recommendations on how one should approach the kind of conditional codegen I'm using that macro for? If not, I can certainly open an issue with a minimal reproducer and try to implement a fix.

**Comment by josevalim** [comment] 2023-06-27 21:56
Can you please try main/v1.15 branches? We have had some bug fixes in the compiler, so this may have been fixed.

**Comment by bitwalker** [comment] 2023-06-27 22:17
@josevalim Looks like the latest on both `main` (as of 587a0a9) and `v1.15` still exhibits the issue

**Comment by josevalim** [comment] 2023-06-28 09:56
The issue is the modification to the application environment you are doing in the mix.exs. Because you modify the app environment project only when the project is compiled (i.e. when the mix.exs is loaded), the compile environment is never reproduced, and hence it detects it went stale and a recompilation is needed.

You should move that code (and the raising) to `lib` and stop modifying the environment. :)

**Comment by bitwalker** [comment] 2023-06-28 16:22
Ah, that makes sense, I had thought  that because I was setting both the compile env and runtime env that it wouldn't be an issue, but your explanation makes sense. 

I can probably release a new minor version that removes that code now, since we're up to OTP 26 now anyway

**Comment by bitwalker** [comment] 2023-06-29 20:12
@sondr3 This is fixed in 0.6.0. Heads up that 0.6.0 has a minimum dependency on Elixir 1.13 and OTP 23.

**Closed by bitwalker** 2023-06-29 20:12 UTC
